In [1]:

import numpy as np
from mxnetnet import MXNetNet
from pytorchnet import PytorchNet
from tfnet import TFNet
        
class ConvBenchmark:
    def __init__(self, **bench_args):
        convweights = bench_args["convweights"]
        self.conv_filters_ = []
        for w in convweights:
            w_array = np.random.random(w).astype(np.float32)
            self.conv_filters_.append(w_array)        
        
        if "poolings" in bench_args:
            self.poolings_ = bench_args["poolings"]
        else:
            self.poolings_ = False
        
        self.networks_ = {}
        self.networks_["pytorchCNN"] = PytorchNet(self.conv_filters_, self.poolings_)
        self.networks_["TF_CNN"] = TFNet(self.conv_filters_, self.poolings_)
        self.networks_["MXNet_CNN"] = MXNetNet(self.conv_filters_, self.poolings_)
        
        self.input_ = np.random.random(bench_args["inputsize"]).astype(np.float32)
        self.results_ = {}
        
    def runNetworks(self):
        # Pytorch nn.Conv2d takes input a 4D Tensor of [nSamples x nChannels x Height x Width]
        # Input is defined in Pytorch layout fashion
        for netname, network in self.networks_.items():
            output, t = network.forward(np.copy(self.input_))
            self.results_[netname] = {"output": output, "runtime": t}
            print("{} took {:.5} seconds.".format(netname, t))
            
        

/kuacc/users/ccengiz17/.anaconda3/envs/dl_frameworks/lib/python3.6/site-packages/tensorflow/python/util/tf_inspect.py:75: DeprecationWarning: inspect.getargspec() is deprecated since Python 3.0, use inspect.signature() or inspect.getfullargspec()
  return _inspect.getargspec(target)


In [2]:
# input is a 4D Tensor of [nSamples x nChannels x Height x Width]
inBS, inCh, inHeight, inWidth = (2,1,32,32)
inputsize = inBS, inCh, inHeight, inWidth

# Filters are 4D tensor in form [out_channels, in_channels, fil_height, fil_width]
conv1w = (6, 1, 5, 5)
conv2w = (16, 6, 5, 5)
convweights = (conv1w, conv2w)

poolings = (2,2)

benchmark = ConvBenchmark(inputsize=inputsize, convweights=convweights, poolings=poolings)

In [3]:
#benchmark = ConvBenchmark(inputsize=(256,3,32,32), convweights=((512, 3, 3, 3), (1024, 512, 3, 3)), poolings=(2,2))

In [4]:
benchmark.runNetworks()

pytorchCNN took 0.049092 seconds.
TF_CNN took 0.052712 seconds.
MXNet_CNN took 0.014765 seconds.


In [5]:
pytorch_out = benchmark.results_["pytorchCNN"]["output"]
mxnet_out = benchmark.results_["MXNet_CNN"]["output"]
tf_out = benchmark.results_["TF_CNN"]["output"]

In [6]:
print(pytorch_out.shape)
print(type(pytorch_out))

(2, 16, 5, 5)
<class 'numpy.ndarray'>


In [7]:
print(mxnet_out.shape)
print(type(mxnet_out))

(2, 16, 5, 5)
<class 'numpy.ndarray'>


In [8]:
print(tf_out.shape)
print(type(tf_out))

(2, 16, 5, 5)
<class 'numpy.ndarray'>


In [9]:
pytorch_out[0,0,0:3,0:3]

array([[ 526.39727783,  509.75863647,  498.75335693],
       [ 508.34094238,  477.66226196,  488.10797119],
       [ 456.0531311 ,  433.68222046,  465.87567139]], dtype=float32)

In [10]:
mxnet_out[0,0,0:3,0:3]

array([[ 526.39727783,  509.75863647,  498.75335693],
       [ 508.34094238,  477.66226196,  488.10797119],
       [ 456.0531311 ,  433.68222046,  465.87567139]], dtype=float32)

In [11]:
tf_out[0,0,0:3,0:3]

array([[ 526.39727783,  509.75863647,  498.75335693],
       [ 508.34094238,  477.66226196,  488.10797119],
       [ 456.0531311 ,  433.68222046,  465.87567139]], dtype=float32)

In [12]:
np.isclose(mxnet_out, pytorch_out, atol=0.001).all()

True

In [13]:
np.isclose(mxnet_out, tf_out, atol=0.001).all()

True

In [14]:
np.isclose(tf_out, pytorch_out, atol=0.001).all()

True